// ffffff
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Author.java
//  @ Date : 11/19/2013
//  @ Author : 
//
//




public class Author
{
    public Object ID;
}
