//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Books.java
//  @ Date : 11/19/2013
//  @ Author : 
//
//




public class Books extends LibaryItem
{
    public Object ISBN;
}
