//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Borrowing.java
//  @ Date : 11/19/2013
//  @ Author : 
//
//




public class Borrowing
{
    public Object checkInDate;
    public Object checkOutDate;
}
