//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LibaryItem.java
//  @ Date : 11/19/2013
//  @ Author : 
//
//




public class LibaryItem
{
    public Object copyID;
    public Object title;
    public Object isAvalibale;
    public Object maxBorrow;
}
