//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Magazines.java
//  @ Date : 11/19/2013
//  @ Author : 
//
//




public class Magazines extends LibaryItem
{
    public Object issueNumber;
}
