//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Member.java
//  @ Date : 11/19/2013
//  @ Author : 
//
//




public class Member
{
    public Object address;
    public Object name;
    public Object phoneNumber;
}
