//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Reservation.java
//  @ Date : 11/19/2013
//  @ Author : 
//
//




public class Reservation
{
    public Object Date;
}
